using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Lab_5___Nisses_stugby
{
    /// <summary>
    /// Interaction logic for Administration.xaml
    /// </summary>
    public partial class Administration : Page
    {
        Labb5Entities dataEntities = new Labb5Entities();
        public Administration()
        {
            InitializeComponent();
            PeopleDatagrid.ItemsSource = dataEntities.People.ToList();
        }

        private void PeopleDatagrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            PeopleDatagrid.Columns[0].Visibility = Visibility.Hidden;
            var a = PeopleDatagrid.Columns;
        }

        //Commits the edits of a row to the database
        private void PeopleDatagrid_RowEditEnding(object sender, DataGridRowEditEndingEventArgs e)
        {
            var i = e.Row.GetIndex();
            if (PeopleDatagrid.SelectedItem != null)
            {
                PeopleDatagrid.RowEditEnding -= PeopleDatagrid_RowEditEnding;
                PeopleDatagrid.CommitEdit();
                PeopleDatagrid.Items.Refresh();
                PeopleDatagrid.RowEditEnding += PeopleDatagrid_RowEditEnding;
            }
            Person editedRow = (Person)PeopleDatagrid.Items[i];
            Person person = dataEntities.People.Find(editedRow.Id);
            person = editedRow;
            dataEntities.SaveChanges();
        }

        private void PeopleDatagrid_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Delete)
            {
                if (PeopleDatagrid.SelectedItem != null)
                {
                    Person selectedPerson = dataEntities.People.Find(((Person)PeopleDatagrid.SelectedItem).Id);
                    dataEntities.People.Remove(selectedPerson);
                    dataEntities.SaveChanges();
                }
            }
        }
    }
}
