//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_5___Nisses_stugby
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cabins
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumOfBeds { get; set; }
        public Nullable<int> NumOfRooms { get; set; }
        public Nullable<int> Size { get; set; }
        public string WIFI { get; set; }
        public string Kitchen { get; set; }
    }
}
